"""Added embedding_vector to Prompts table

Revision ID: 8ebac05ce589
Revises: b4d831c4fb66
Create Date: 2024-09-29 11:08:44.475588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ebac05ce589'
down_revision = 'b4d831c4fb66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_vector', postgresql.ARRAY(sa.Float()), nullable=True))

    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_vector', postgresql.ARRAY(sa.Float()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_column('embedding_vector')

    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_column('embedding_vector')

    # ### end Alembic commands ###
